import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,cp,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {reconcile} from '../scripts/sync-community-public.mjs';
import {fixture,ids,attack} from './fixtures/community-publish/source.mjs';
const options={skip:!(process.env.BROWSER_TEST_MODULE&&process.env.BROWSER_TEST_EXECUTABLE)&&'Configure real Chrome mobile tests.'};
async function safeMobile(page,label){const result=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,offenders:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,8).map(e=>e.id||e.className)}));assert.ok(result.width<=375,label+JSON.stringify(result));assert.equal(await page.evaluate(()=>window.compromised),undefined);}
test('Round 5 actual Chrome 375px: Community/static/legacy authors, article text/media/social identity, moment anchors, album/lightbox/discussion, search',options,async()=>{
 const directory=await mkdtemp('/tmp/community-round5-browser-'),f=fixture();await cp(new URL('../',import.meta.url),directory,{recursive:true,filter:s=>!/(?:^|\/)(?:\.git|node_modules)(?:\/|$)/.test(s)});await reconcile({adapter:f.adapter,directory});execFileSync(process.execPath,['scripts/generate-site.mjs'],{cwd:directory,stdio:'pipe'});
 const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost'),file=path.resolve(directory,'.'+u.pathname);if(!file.startsWith(directory+'/'))throw Error('Path');res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const imported=await import(process.env.BROWSER_TEST_MODULE),chromium=imported.chromium||imported.default.chromium,browser=await chromium.launch({executablePath:process.env.BROWSER_TEST_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']}),base='http://127.0.0.1:'+server.address().port;
 try{const page=await browser.newPage({viewport:{width:375,height:812}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const scripts={
 'auth.js':`window.BlogAuth={ready:async()=>{},configured:()=>false,user:()=>({id:'${ids.author}'}),isAdmin:()=>false,requireUser(){return this.user();},requireAdmin(){throw Error('Admin required');},signOut:async()=>{},client:()=>({rpc:async()=>({data:[{id:'40000009-0000-4000-8000-000000000009',username:'member_user',display_name:'投稿作者',content:${JSON.stringify(attack+'x'.repeat(600))},created_at:'2026-10-07',author_id:'${ids.author}'}]})})};`,
 'blog-data.js':`window.__social=[];window.BlogData={getProfile:async()=>({username:'member_user',display_name:'投稿作者'}),likes:async(type,ids)=>Object.fromEntries(ids.map(id=>[id,{count:1,liked:false}])),toggleLike:async(type,id)=>{window.__social.push(['like',type,id]);return true;},addComment:async(slug,body,parent)=>window.__social.push(['comment',slug,body,parent]),listComments:async()=>[],listLatestComments:async()=>[],listModeration:async()=>[],messageUnreadCount:async()=>0};`
 };
 await page.route('**/*',async route=>{const url=new URL(route.request().url()),script=scripts[url.pathname.split('/').at(-1)];if(script){await route.fulfill({contentType:'text/javascript',body:script});return;}if(url.hostname==='fixture.supabase.invalid'){await route.fulfill({contentType:'image/jpeg',body:await readFile(directory+'/assets/avatar-default.jpg')});return;}if(url.hostname!=='127.0.0.1'){await route.abort();return;}await route.continue();});
 for(const route of ['index.html','archive.html?category='+encodeURIComponent('测试分类'),'timeline.html']){await page.goto(base+'/'+route);await page.waitForFunction(()=>document.body.textContent.includes('投稿作者'),null,{timeout:5000}).catch(async e=>{throw Error(route+': '+JSON.stringify(errors)+' '+await page.evaluate(()=>JSON.stringify({items:window.COMMUNITY_PUBLIC&&window.COMMUNITY_PUBLIC.items.length,text:document.body.textContent.slice(-200)})));});await safeMobile(page,route);assert.ok(await page.locator('a[href="posts/community-first-article.html"]').count());}
 await page.goto(base+'/posts/community-first-article.html');await page.waitForFunction(()=>document.getElementById('postContent').textContent.includes('window.compromised'));await safeMobile(page,'article');assert.equal(await page.locator('#postContent script, #postContent [onerror]').count(),0);assert.match(await page.locator('#postAuthor').textContent(),/member_user/);assert.equal(await page.locator('#commentsSection').getAttribute('data-slug'),'community-'+ids.article);await page.locator('#likeBtn').click();assert.deepEqual(await page.evaluate(()=>window.__social[0]),['like','content',ids.article]);
 await page.locator('#commentContent').fill('new approved-target comment');await page.locator('#commentForm button[type=submit]').click();await page.waitForFunction(()=>window.__social.some(c=>c[0]==='comment'));assert.equal((await page.evaluate(()=>window.__social.find(c=>c[0]==='comment')))[1],'community-'+ids.article);
 await page.goto(base+'/moments.html#community-'+ids.moment);await page.waitForSelector('#community-'+ids.moment);await safeMobile(page,'moment');assert.match(await page.locator('#community-'+ids.moment+' .moment-name').textContent(),/member_user/);assert.match(await page.locator('.moment-name').last().textContent(),/hshspacex/);await page.locator('#community-'+ids.moment+' [data-like]').click();assert.equal((await page.evaluate(()=>window.__social[0]))[1],'content');await page.locator('#community-'+ids.moment+' [data-comments]').click();await page.waitForSelector('#comments-'+ids.moment+' textarea');await safeMobile(page,'moment comments');
 await page.goto(base+'/gallery.html');await page.waitForSelector('.album-card');await safeMobile(page,'album cards');assert.match(await page.locator('.album-card').textContent(),/member_user/);assert.equal(await page.locator('.album-cover-link').getAttribute('href'),'gallery.html?community='+ids.album);await page.locator('.album-cover-link').click();await page.waitForSelector('#communityDiscussion .public-content-card');await safeMobile(page,'album discussion');await page.locator('[data-photo-index="0"]').click();await page.waitForFunction(()=>!document.getElementById('lightbox').hidden);await safeMobile(page,'lightbox');assert.ok((await page.locator('#lightboxCaption').textContent()).includes('<script>'));await page.keyboard.press('Escape');
 await page.goto(base+'/search.html?q='+encodeURIComponent('测试分类'));await page.waitForSelector('a[href="posts/community-first-article.html"]');await safeMobile(page,'search');assert.ok((await page.locator('body').textContent()).includes('社区文章'));assert.deepEqual(errors,[]);await page.close();
 }finally{await browser.close();await new Promise(r=>server.close(r));await rm(directory,{recursive:true,force:true});}
});
