import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createNativeDatabase,nativeConfigured} from './helpers/native-postgres.mjs';
import {asActor,seedActors,actors} from './helpers/postgres.mjs';
const {user,other,admin}=actors,options={skip:!nativeConfigured&&'Configure isolated native PostgreSQL.'};
const run=(db,id,sql,args=[])=>asActor(db,id?'authenticated':'anon',id,sql,args);
async function service(db,sql,args=[]){await db.exec('begin;set local role service_role');try{const result=await db.query(sql,args);await db.exec('commit');return result;}catch(e){await db.exec('rollback');throw e;}}
async function create(db,type='article',body={text:'public text',category:'投稿分类'}){const item=(await run(db,user,'select public.community_create_item($1,$2) as id',[type,'test-'+randomUUID()])).rows[0].id;const revision=(await run(db,user,'select public.community_save_revision($1,$2,$3) as id',[item,'Title',body])).rows[0].id;await run(db,user,'select public.community_submit_revision($1)',[revision]);return {item,revision};}
test('Round 5 native PostgreSQL: current approved authority, private publication states, CAS results, schema/category and real public/social routes',options,async()=>{
 const db=await createNativeDatabase();try{await seedActors(db);const a=await create(db);assert.deepEqual((await service(db,'select public.community_publication_export() as rows')).rows[0].rows,[]);
 for(const id of [null,user,other,admin])await assert.rejects(run(db,id,'select public.community_publication_export()'),/permission denied/);
 await run(db,admin,'select public.community_review_revision($1,$2,$3)',[a.revision,'approved',null]);
 let rows=(await service(db,'select public.community_publication_export() as rows')).rows[0].rows;assert.equal(rows.length,1);assert.equal(rows[0].revision_id,a.revision);assert.deepEqual(Object.keys(rows[0].author).sort(),['avatar_url','display_name','username']);assert.doesNotMatch(JSON.stringify(rows),/email|user_metadata|Auth/);
 assert.equal((await run(db,user,'select status from public.community_publication_state')).rows[0].status,'pending');assert.equal((await run(db,other,'select * from public.community_publication_state')).rows.length,0);assert.equal((await run(db,admin,'select * from public.community_publication_state')).rows.length,1);
 for(const id of [user,admin]){await assert.rejects(run(db,id,"update public.community_publication_state set status='published'"),/permission denied/);await assert.rejects(run(db,id,'select public.community_publication_result($1,$2,$3,$4,$5)',[a.item,a.revision,'published','a'.repeat(40),null]),/permission denied/);await assert.rejects(run(db,id,'select * from public.community_publication_config'),/permission denied/);}
 await assert.rejects(run(db,null,'select * from public.community_publication_state'),/permission denied/);
 await service(db,'select public.community_publication_result($1,$2,$3,$4,$5)',[a.item,a.revision,'published','a'.repeat(40),null]);assert.equal((await run(db,user,'select status,published_revision_id from public.community_publication_state')).rows[0].published_revision_id,a.revision);
 const edit=(await run(db,user,'select public.community_save_revision($1,$2,$3) as id',[a.item,'new',{text:'PRIVATE_PENDING'}])).rows[0].id;await run(db,user,'select public.community_submit_revision($1)',[edit]);rows=(await service(db,'select public.community_publication_export() as rows')).rows[0].rows;assert.equal(rows[0].revision_id,a.revision);assert.doesNotMatch(JSON.stringify(rows),/PRIVATE_PENDING/);
 await run(db,admin,'select public.community_review_revision($1,$2,$3)',[edit,'rejected','private reason']);assert.doesNotMatch(JSON.stringify((await service(db,'select public.community_publication_export() as rows')).rows[0].rows),/private reason|PRIVATE_PENDING/);
 const newer=(await run(db,user,'select public.community_save_revision($1,$2,$3) as id',[a.item,'new public',{text:'NEW_PUBLIC'}])).rows[0].id;await run(db,user,'select public.community_submit_revision($1)',[newer]);await run(db,admin,'select public.community_review_revision($1,$2,$3)',[newer,'approved',null]);assert.equal((await run(db,user,'select status from public.community_publication_state')).rows[0].status,'pending');assert.equal((await service(db,'select public.community_publication_result($1,$2,$3,$4,$5) as ok',[a.item,a.revision,'published','a'.repeat(40),null])).rows[0].ok,false);
 await assert.rejects(service(db,'select public.community_publication_result($1,$2,$3,$4,$5)',[a.item,newer,'failed',null,'secret fixture detail']),/check constraint/);await service(db,'select public.community_publication_result($1,$2,$3,$4,$5)',[a.item,newer,'failed',null,'INVALID_MEDIA']);assert.equal((await run(db,user,'select last_error from public.community_publication_state')).rows[0].last_error,'INVALID_MEDIA');
 await run(db,user,"insert into public.likes(user_id,target_type,target_id) values($1,'content',$2)",[user,a.item]);assert.equal((await run(db,null,'select public.profile_recent_likes($1,20,0) as card',[user])).rows[0].card.target_path.startsWith('posts/test-'),true);
 for(const [type,body,route] of [['moment',{text:'moment'},'moments.html#community-']]){const m=await create(db,type,body);await run(db,admin,'select public.community_review_revision($1,$2,$3)',[m.revision,'approved',null]);assert.equal((await run(db,null,'select public.profile_content($1,$2,20,0) as card',[user,type])).rows[0].card.target_path,route+m.item);}
 for(const category of ['', 'x'.repeat(41),'<img>'])await assert.rejects(run(db,user,'select public.community_save_revision($1,$2,$3)',[a.item,'invalid',{text:'x',category}]),/Invalid article category/);
 await db.query('delete from auth.users where id=$1',[user]);assert.deepEqual((await service(db,'select public.community_publication_export() as rows')).rows[0].rows,[]);assert.equal((await db.query('select * from public.community_publication_state')).rows.length,0);
 }finally{await db.close();}
});
test('Round 5 native Storage: public read, restrictive user/admin writes, private originals stay private; trusted legacy owner config/upsert/remove',options,async()=>{
 const db=await createNativeDatabase();try{await seedActors(db);assert.equal((await db.query("select public from storage.buckets where id='published-media'")).rows[0].public,true);assert.equal((await db.query("select count(*)::int n from storage.buckets where id in ('community-assets','dm-media') and not public")).rows[0].n,2);
 // Simulate an accidentally broad policy: restrictive guards must still win.
 await db.exec("create policy fixture_broad_storage on storage.objects for all to anon,authenticated using(true) with check(true)");const object=(await db.query("insert into storage.objects(bucket_id,name,metadata) values('published-media','community/public.png','{}') returning id")).rows[0].id;
 for(const id of [null,user,other,admin]){assert.equal((await run(db,id,'select * from storage.objects where id=$1',[object])).rows.length,1);await assert.rejects(run(db,id,"insert into storage.objects(bucket_id,name) values('published-media','attack.png')"),/row-level security/);assert.equal((await run(db,id,"update storage.objects set name='attack.png' where id=$1 returning id",[object])).rows.length,0);assert.equal((await run(db,id,'delete from storage.objects where id=$1 returning id',[object])).rows.length,0);}
 const owned=user+'/'+randomUUID()+'.png',privateObject=(await run(db,user,"insert into storage.objects(bucket_id,name,metadata) values('community-assets',$1,$2) returning id",[owned,{mimetype:'image/png',size:12}])).rows[0].id;for(const id of [null,other])assert.equal((await run(db,id,'select * from storage.objects where id=$1',[privateObject])).rows.length,0);
 const targets=[{target_type:'post',target_id:'trusted-fixture',title:'Legacy title',excerpt:'Excerpt',target_path:'posts/trusted-fixture.html',published_at:'2026-10-07'}];
 for(const id of [null,user,admin])await assert.rejects(run(db,id,'select public.community_sync_legacy_targets($1)',[JSON.stringify(targets)]),/permission denied/);
 await service(db,'select public.community_sync_legacy_targets($1)',[JSON.stringify(targets)]);assert.equal((await db.query("select author_id from public.legacy_public_targets where target_id='trusted-fixture'")).rows[0].author_id,null);
 await service(db,'update public.community_publication_config set legacy_author_id=$1',[admin]);await service(db,'select public.community_sync_legacy_targets($1)',[JSON.stringify(targets)]);assert.equal((await db.query("select author_id from public.legacy_public_targets where target_id='trusted-fixture'")).rows[0].author_id,admin);
 await run(db,user,"insert into public.likes(user_id,target_type,target_id) values($1,'post','trusted-fixture')",[user]);assert.equal((await run(db,admin,"select * from public.notifications where type='content_like'")).rows.length,1);
 targets[0].title='Updated';await service(db,'select public.community_sync_legacy_targets($1)',[JSON.stringify(targets)]);assert.equal((await db.query("select title from public.legacy_public_targets where target_id='trusted-fixture'")).rows[0].title,'Updated');await service(db,'select public.community_sync_legacy_targets($1)',['[]']);assert.equal((await db.query('select * from public.legacy_public_targets')).rows.length,0);
 assert.equal((await db.query('select * from storage.objects where id=$1',[privateObject])).rows.length,1);
 }finally{await db.close();}
});
