import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
const configured=process.env.BROWSER_TEST_MODULE&&process.env.BROWSER_TEST_EXECUTABLE;
const options={skip:!configured&&'Configure a real Chromium browser.'};
const uid='00000001-0000-4000-8000-000000000001',asset='00000002-0000-4000-8000-000000000002';
const sizes=[[1440,900],[1024,768],[768,1024],[375,812]];
async function serve(){const server=createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname),relative=path.relative(root,file);if(relative.startsWith('..')||path.isAbsolute(relative))throw Error('Path');res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));return {server,base:'http://127.0.0.1:'+server.address().port};}
async function fixtures(page,role='user',missing=false){
 const profile={id:uid,username:'test_user',display_name:'测试作者',bio:'生活与创作',avatar_url:'assets/avatar-default.jpg'};
 const scripts={
 'auth.js':`window.__actor={id:'${uid}',email:'test@example.invalid'};window.__admin=${role==='admin'};window.BlogAuth={ready:async()=>{},user:()=>window.__actor,configured:()=>true,isAdmin:()=>!!window.__actor&&window.__admin,requireUser(){if(!this.user())throw Error('Login required');return this.user();},requireAdmin(){if(!this.isAdmin())throw Error('Admin required');return this.user();},signOut:async()=>{window.__actor=null;document.dispatchEvent(new Event('blog-auth-change'));},resetPassword:async()=>{}};`,
 'blog-data.js':`window.BlogData={getProfile:async()=>(${JSON.stringify(profile)}),notificationCount:async()=>3,dmUnreadCount:async()=>{${missing?"throw Object.assign(Error('Could not find the function public.dm_unread_count in the schema cache'),{code:'PGRST202'})":"return 2"};},messageUnreadCount:async()=>5,followerCount:async()=>4,following:async()=>false,toggleFollow:async()=>true,likes:async()=>({}),listComments:async()=>[],listLatestComments:async()=>[],listModeration:async()=>[],listNotifications:async()=>[],markNotificationsRead:async()=>{}};`,
 'community-data.js':`window.__revs=JSON.parse(sessionStorage.getItem('fixture-revs')||'{}');window.__items=JSON.parse(sessionStorage.getItem('fixture-items')||'{}');window.__saves=[];const persist=()=>{sessionStorage.setItem('fixture-revs',JSON.stringify(window.__revs));sessionStorage.setItem('fixture-items',JSON.stringify(window.__items));};const files=[{id:'${asset}',original_name:'我的图片.png',mime_type:'image/png',size_bytes:100,reference_count:0}];window.CommunityData={errorMessage:e=>e.code==='PGRST202'?'当前 Supabase 环境缺少表或 RPC，请站长执行 migrations 并核对项目。操作未完成。':e.message,listItems:async()=>{${missing?"throw Object.assign(Error('当前 Supabase 环境尚未部署，请站长执行 migrations。'),{code:'PGRST205'})":"return Object.values(window.__items).map(i=>({...i,content_revisions:Object.values(window.__revs).filter(r=>r.item_id===i.id).slice(-1)}))"};},listAssets:async()=>files,assetsPage:async()=>files,orphans:async()=>[],listReviews:async()=>[],create:async(type,slug,title,body)=>{const i={id:crypto.randomUUID(),author_id:'${uid}',content_type:type,slug};window.__items[i.id]=i;return window.CommunityData.save(i,title,body);},save:async(item,title,body)=>{const id=crypto.randomUUID();window.__revs[id]={id,item_id:item.id,title,body:structuredClone(body),status:'draft',content_items:item};window.__saves.push(body);persist();return id;},getRevision:async id=>{if(!window.__revs[id])throw Error('无权访问');return structuredClone(window.__revs[id]);},submit:async id=>{window.__revs[id].status=window.__admin?'approved':'pending';persist();},signedAsset:async()=>({asset:files[0],url:location.origin+'/assets/avatar-default.jpg',expiresAt:Date.now()+60000})};`,
 'comment-edit-data.js':`window.CommentEditData={mine:async()=>[],queue:async()=>[]};`,
 'public-profile-data.js':`window.PublicProfileData={profile:async()=>(${JSON.stringify(profile)}),counts:async()=>[4,2],legacy:()=>[],content:async(id,type,offset)=>Array.from({length:offset?1:20},()=>({kind:type,title:'公开作品',text:'已公开内容',target_path:'moments.html#moment-test',username:'test_user',display_name:'测试作者'})),followers:async()=>[${JSON.stringify(profile)}],following:async()=>[${JSON.stringify(profile)}],likes:async()=>[],resolveLegacy:r=>r};`,
 'message-data.js':`window.MessageData={threads:async()=>[],unsent:async()=>[],orphans:async()=>[],unread:async()=>2,uuid:id=>/^[0-9a-f-]{36}$/.test(id||'')};`,
 'github-credentials.js':`window.GitHubCredentials={get:()=>window.__admin?'fixture-only':'',clear(){},validate:async()=>{},connect:async()=>{}};`
 };
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname!=='127.0.0.1'){await route.abort();return;}const script=scripts[url.pathname.split('/').at(-1)];if(script)await route.fulfill({contentType:'text/javascript',body:script});else await route.continue();});
}
async function layout(page,label){const result=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,visible:[...document.querySelectorAll('[data-workspace-panel]')].filter(p=>!p.hidden).map(p=>p.id)}));assert.ok(result.width<=result.viewport,label+' overflow: '+JSON.stringify(result));assert.equal(result.visible.length,1,label+' only one independent module');}
async function navigate(page,route){await page.evaluate(r=>window.AccountRoute.navigate(r),route);await page.waitForFunction(r=>document.getElementById('accountSections').dataset.activeModule===r,route);}

test('real Chromium workspace: four widths, user/admin shared editor, routes/history/drafts, resource selection, saves, previews, themes and private clearing',options,async()=>{
 const {server,base}=await serve(),imported=await import(process.env.BROWSER_TEST_MODULE),browser=await imported.chromium.launch({executablePath:process.env.BROWSER_TEST_EXECUTABLE,headless:true});
 try{for(const role of ['user','admin'])for(const [width,height]of sizes){const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await fixtures(page,role);await page.goto(base+'/account.html#content');await page.waitForFunction(()=>document.getElementById('content').hidden===false);await layout(page,role+' '+width);
  assert.equal(await page.locator('#communityRichEditor').getAttribute('data-editor-core'),'shared-v1');
  assert.equal(await page.locator('#accountAdminNav a').count(),role==='admin'?4:0);
  await page.locator('#directoryToggle').click();assert.equal(await page.locator('#directoryToggle').getAttribute('aria-expanded'),'true');await page.locator('[data-workspace-route="assets"]').click();await page.waitForFunction(()=>!document.getElementById('assets').hidden);await layout(page,'assets');
  if(width===375)assert.equal(await page.locator('#directoryToggle').getAttribute('aria-expanded'),'false');
  await navigate(page,'articles');await page.locator('[data-new-content="article"]').click();await page.locator('#communityTitle').fill('共享编辑器文章');await page.locator('#communityRichEditor').fill('未保存草稿 <script>window.compromised=1</script>');
  await navigate(page,'assets');await navigate(page,'articles');assert.match(await page.locator('#communityRichEditor').textContent(),/未保存草稿/);
  await page.goBack();await page.waitForFunction(()=>!document.getElementById('assets').hidden);await page.goForward();await page.waitForFunction(()=>!document.getElementById('content').hidden);
  await page.locator('#communityRichEditor').click();await page.keyboard.press('Control+a');await page.locator('[data-editor-tool="bold"]').click();
  await page.locator('#communityChooseAssets').click();await page.locator('#resourcePickerList button').first().click();assert.equal(await page.locator('#communityResourcePicker').evaluate(d=>d.open),false);
  await page.locator('#communityTextPreview').click();assert.ok((await page.locator('#communityPreviewBody').textContent()).includes('<script>'));assert.equal(await page.locator('#communityPreviewBody script, #communityPreviewBody [onerror]').count(),0);
  await page.locator('#communitySave').click();await page.waitForFunction(()=>document.getElementById('communityStatus').textContent.includes('草稿已保存'));const body=await page.evaluate(()=>window.__saves.at(-1));assert.equal(body.document.version,1);assert.equal(body.asset_ids[0],asset);assert.ok(body.document.blocks.some(b=>b.type==='asset'));
  await page.locator('#communitySubmit').click();await page.waitForFunction(()=>document.getElementById('communityStatus').textContent.includes('提交成功'));assert.match(await page.locator('#communityPreviewState').textContent(),role==='admin'?/approved/:/pending/);
  for(const type of ['moment','album']){await navigate(page,type==='moment'?'moments':'albums');await page.locator('[data-new-content="'+type+'"]').click();await page.locator('#communityTitle').fill(type+'作品');await page.locator('#communityRichEditor').fill('真实浏览器输入的说明');if(type==='album')await page.locator('[data-asset-choice]').first().check();await page.locator('#communitySave').click();await page.waitForFunction(()=>document.getElementById('communityStatus').textContent.includes('草稿已保存'));}
  for(const route of ['my-comments','notifications','direct-messages','connections','security']){await navigate(page,route);await layout(page,route);}
  await navigate(page,'articles');await page.locator('#themeToggle').click();await page.locator('#directoryToggle').click();await layout(page,'dark');
  if(process.env.GUI_EVIDENCE_DIR){await mkdir(process.env.GUI_EVIDENCE_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.GUI_EVIDENCE_DIR,role+'-'+width+'-dark.png'),fullPage:true});if(width===375)await page.keyboard.press('Escape');await page.locator('#themeToggle').click();await page.screenshot({path:path.join(process.env.GUI_EVIDENCE_DIR,role+'-'+width+'-light.png'),fullPage:true});}
  await page.reload();await page.waitForFunction(()=>!document.getElementById('content').hidden);assert.equal(await page.evaluate(()=>document.querySelectorAll('[data-workspace-panel]:not([hidden])').length),1);
  await page.evaluate(()=>{window.__actor={id:'00000003-0000-4000-8000-000000000003'};window.__admin=false;document.dispatchEvent(new Event('blog-auth-change'));});await page.waitForFunction(()=>document.getElementById('communityRichEditor').textContent==='');assert.equal(await page.locator('#accountAdminNav a').count(),0);assert.equal(await page.evaluate(()=>window.compromised),undefined);assert.deepEqual(errors,[]);await page.close();
 }}finally{await browser.close();await new Promise(r=>server.close(r));}
});

test('real Chromium: missing backend is explicit and leaves the directory usable; legacy HTML uses the same editor core without losing content',options,async()=>{
 const {server,base}=await serve(),imported=await import(process.env.BROWSER_TEST_MODULE),browser=await imported.chromium.launch({executablePath:process.env.BROWSER_TEST_EXECUTABLE,headless:true});
 try{const page=await browser.newPage({viewport:{width:1440,height:900}});await fixtures(page,'admin',true);await page.goto(base+'/account.html');await page.waitForFunction(()=>document.getElementById('accountStatus').textContent.includes('migrations'));await navigate(page,'articles');await page.waitForFunction(()=>document.getElementById('communityStatus').textContent.includes('尚未部署'));await layout(page,'backend unavailable');await page.goto(base+'/admin.html?preview=1');await page.waitForFunction(()=>!document.getElementById('appPanel').hidden);await page.locator('#legacyDirectoryToggle').click();await page.locator('#postList [data-edit]').first().click();await page.waitForFunction(()=>!document.getElementById('editorPanel').hidden);assert.equal(await page.locator('#richEditor').getAttribute('data-editor-core'),'shared-v1');assert.ok((await page.locator('#richEditor').textContent()).includes('奥匈'));await page.locator('#previewBtn').click();assert.ok((await page.locator('#previewBody').textContent()).includes('奥匈'));assert.equal(await page.locator('#contentToolbar [data-editor-tool="bold"]').count(),1);assert.equal(await page.locator('#saveBtn').isDisabled(),true);await page.close();
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});

test('real Chromium legacy GitHub save remains functional with intercepted HTTP; no production requests or credentials',options,async()=>{
 const {server,base}=await serve(),imported=await import(process.env.BROWSER_TEST_MODULE),browser=await imported.chromium.launch({executablePath:process.env.BROWSER_TEST_EXECUTABLE,headless:true});
 try{const page=await browser.newPage({viewport:{width:1440,height:900}});await fixtures(page,'admin');let writes=[];const source=await readFile(new URL('../js/posts.js',import.meta.url),'utf8');
 await page.route('https://api.github.com/**',async route=>{const req=route.request(),url=new URL(req.url());assert.equal(url.pathname,'/repos/HSHSpaceX/personal-blog/contents/js/posts.js');assert.match(req.headers().authorization,/^Bearer fixture-only$/);if(req.method()==='PUT'){writes.push(req.postDataJSON());await route.fulfill({json:{content:{sha:'fixture-new-sha'}}});}else await route.fulfill({json:{sha:'fixture-sha',content:Buffer.from(source).toString('base64')}});});
 await page.goto(base+'/admin.html');await page.waitForFunction(()=>!document.getElementById('appPanel').hidden);await page.locator('#postList [data-edit]').first().click();const original=await page.locator('#richEditor').innerHTML();await page.locator('#postTitle').fill('Legacy 测试标题');await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.getElementById('editorStatus').textContent.includes('已保存并提交'));assert.equal(writes.length,1);assert.equal(writes[0].sha,'fixture-sha');assert.equal(writes[0].branch,'main');const committed=Buffer.from(writes[0].content,'base64').toString();assert.match(committed,/Legacy 测试标题/);assert.ok(committed.includes(original.replace(/\\/g,'\\\\').replace(/`/g,'\\`').replace(/\$\{/g,'\\${')));assert.equal(await page.locator('#richEditor').getAttribute('data-editor-core'),'shared-v1');await page.close();
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
